#!/bin/sh
#echo -ne "$(cat /sys/class/power_supply/BAT0/capacity)%"
#printf "%s%%" "$(cat /sys/class/power_supply/BAT0/capacity)"
ls /sys/class/power_supply/BAT* >/dev/null 2>&1 || exit 0
cat /sys/class/power_supply/BAT0/capacity
