#!/usr/bin/env bash

show_bemenu() {
bemenu \
  --center\
  -l 5 \
  --ignorecase \
  -H 26 \
  --width-factor 0.20 \
  --binding 'vim' \
  --vim-esc-exits \
  --monitor '1' \
  --hp '6' \
  --fn 'Nerd Font Mono' \
  --tb '#1e1e2e' \
  --fb '#1e1e2e' \
  --nb '#1e1e2e' \
  --hb '#1e1e2e' \
  --fbb '#1e1e2e' \
  --ab '#1e1e2e' \
  --sb '#1e1e2e' \
  --ff '#f5c2e7' \
  --tf '#7287fd' \
  --sf '#7287fd' \
  --hf '#7287fd' \
  -p 'Network options'
  #--vim-normal-mode \
}

if ip link | grep wg0 &>/dev/null ; then 
    vpn_status="active" 
    dmenu_msg="disable"
    else
    vpn_status="inactive"
    dmenu_msg="enable"
fi

case "$(printf "network config\n$dmenu_msg vpn connection\ncancel" | show_bemenu )" in

    "network config")
        foot --app-id='float-menu' -w 800x700 nmtui 
        ;;
    "$dmenu_msg vpn connection")
        export SUDO_ASKPASS="$HOME/.local/bin/bemenu-pass"
        #call dpass script (bemenu script for password input)
        sudo -A $SUDO_ASKPASS 2>/dev/null
        #[ ip link | grep wg0 &>/dev/null ] && sudo wg-quick down wg0 &>/dev/null || sudo wg-quick down wg0 &>/dev/null
        if [ $vpn_status = "active" ]; then
            sudo wg-quick down wg0 &>/dev/null && # bring interface down (disconnect)   
            notify-send -t 2000 "vpn connection disabled"
        else
            sudo wg-quick up wg0 &>/dev/null	&& # bring interface up (connect)  
            notify-send -t 2000 "vpn connection successfully established"
        fi
        ;;
    cancel)
        exit 0
        ;;
    *)
        exit 1
        ;;
esac

pkill -SIGRTMIN+12 someblocks
