#!/bin/sh

ls /sys/class/power_supply/BAT* >/dev/null 2>&1 || exit 0
# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

#case $BLOCK_BUTTON in
	#3) notify-send "🔋 Battery module" "🔋: discharging
#🛑: not charging
#♻: stagnant charge
#🔌: charging
#⚡: charged
#❗: battery very low!
#- Scroll to change adjust xbacklight." ;;
	#4) xbacklight -inc 10 ;;
	#5) xbacklight -dec 10 ;;
	#6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
#esac

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
		"Full") 
            status="󰁹" 
            print="^fg(#a6e3a1)󰁹^fg()" ;;
        "Discharging") 
            status="󱟞" ;;
            #status="^fg(#fab387)󱟞^fg()" ;;
        "Charging") 
            status="󰂄"
            print="^fg(#a6e3a1)󰂄^fg()" ;;
		"Not charging") 
            status="󱃍 "
            print="^fg(#f38ba8)󱃍^fg()" ;;
		"Unknown") 
            status="󰂑" 
            print="^fg(#f38ba8)󰂑^fg()" ;;
		*) exit 1 ;;
	esac
	capacity="$(cat "$battery/capacity" 2>&1)"
	# Will make a warn variable if discharging and low
	[ "$status" = "󱟞" ] && [ "$capacity" -le 45 ] && print="^fg(#fab387)󱟞^fg()"
	[ "$status" = "󱟞" ] && [ "$capacity" -gt 45 ] && print="^fg(#a6e3a1)󱟞^fg()"
	[ "$status" = "󱟞" ] && [ "$capacity" -gt 80 ] && print="^fg(#a6e3a1)󰁹^fg()"
	[ "$status" = "󰂄" ] && [ "$capacity" -gt 80 ] && notify-send "Battery charge high, unplug to save battery life"
	[ "$status" = "󱟞" ] && [ "$capacity" -le 25 ] && print="^fg(#f38ba8)󰁻^fg()" && notify-send "Battery charge low, please plug in power"
	# Prints the info
	#printf "%s%s %d%%" "$status" "$warn" "$capacity"; unset warn
	printf "%s%s %d%%" "$print" "$warn" "$capacity"; unset warn
done && printf "\\n"
